package com.example.model

import androidx.compose.ui.graphics.Color

enum class CarAudioThemeType(
    val id: String,
    val displayName: String,
    val subtitle: String,
    val primaryColor: Color,
    val accentColor: Color,
    val backgroundColor: Color,
    val surfaceColor: Color,
    val cardColor: Color,
    val onPrimaryColor: Color,
    val textColor: Color,
    val textSecondaryColor: Color,
    val meterPeakColor: Color,
    val clipAlertColor: Color = Color(0xFFFF2222)
) {
    NEON_CYBER(
        id = "neon_cyber",
        displayName = "Cyber Neon Green",
        subtitle = "Estilo Kicker & Monster Bass",
        primaryColor = Color(0xFF00FF66),
        accentColor = Color(0xFF00F0FF),
        backgroundColor = Color(0xFF090D0B),
        surfaceColor = Color(0xFF111A14),
        cardColor = Color(0xFF17241C),
        onPrimaryColor = Color(0xFF00220A),
        textColor = Color(0xFFE5FFE9),
        textSecondaryColor = Color(0xFF88B393),
        meterPeakColor = Color(0xFF00FF66)
    ),
    CRIMSON_RED(
        id = "crimson_red",
        displayName = "Taramps Crimson Red",
        subtitle = "Estilo Stetsom & Taramps Brasil",
        primaryColor = Color(0xFFFF1E27),
        accentColor = Color(0xFFFF6B6B),
        backgroundColor = Color(0xFF0F0708),
        surfaceColor = Color(0xFF1C0E10),
        cardColor = Color(0xFF2B1417),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFFFEBEB),
        textSecondaryColor = Color(0xFFB57D81),
        meterPeakColor = Color(0xFFFF1E27)
    ),
    ELECTRIC_BLUE(
        id = "electric_blue",
        displayName = "Pioneer Cobalt Blue",
        subtitle = "Estilo JL Audio & Pioneer ODR",
        primaryColor = Color(0xFF0088FF),
        accentColor = Color(0xFF00D4FF),
        backgroundColor = Color(0xFF060B14),
        surfaceColor = Color(0xFF0D1726),
        cardColor = Color(0xFF142238),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFE6F3FF),
        textSecondaryColor = Color(0xFF7B9CBD),
        meterPeakColor = Color(0xFF00B4FF)
    ),
    CARBON_GOLD(
        id = "carbon_gold",
        displayName = "Soundigital Gold Edition",
        subtitle = "Estilo Digital Designs Carbon & Gold",
        primaryColor = Color(0xFFFFC107),
        accentColor = Color(0xFFFFE082),
        backgroundColor = Color(0xFF0E0D08),
        surfaceColor = Color(0xFF1A170F),
        cardColor = Color(0xFF262215),
        onPrimaryColor = Color(0xFF2B2000),
        textColor = Color(0xFFFFF8E1),
        textSecondaryColor = Color(0xFFB5A986),
        meterPeakColor = Color(0xFFFFD54F)
    ),
    ULTRA_VIOLET(
        id = "ultra_violet",
        displayName = "Orion HCCA Purple",
        subtitle = "Estilo Heavy Subwoofer High Voltage",
        primaryColor = Color(0xFFB537F2),
        accentColor = Color(0xFFE040FB),
        backgroundColor = Color(0xFF0D0614),
        surfaceColor = Color(0xFF180D24),
        cardColor = Color(0xFF261538),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFF7EBFF),
        textSecondaryColor = Color(0xFFA685BD),
        meterPeakColor = Color(0xFFD500F9)
    ),
    BLAZE_ORANGE(
        id = "blaze_orange",
        displayName = "Sundown Blaze Orange",
        subtitle = "Estilo Sundown Audio & Basshead",
        primaryColor = Color(0xFFFF6600),
        accentColor = Color(0xFFFF9E40),
        backgroundColor = Color(0xFF120A04),
        surfaceColor = Color(0xFF211308),
        cardColor = Color(0xFF331C0C),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFFFECE0),
        textSecondaryColor = Color(0xFFB8947C),
        meterPeakColor = Color(0xFFFF6D00)
    ),
    ACID_LIME(
        id = "acid_lime",
        displayName = "Toxic Acid Lime",
        subtitle = "Estilo B2 Audio & SPL Competencia",
        primaryColor = Color(0xFFB8FF00),
        accentColor = Color(0xFFD4FF5E),
        backgroundColor = Color(0xFF0A0F03),
        surfaceColor = Color(0xFF141F06),
        cardColor = Color(0xFF1F2F0A),
        onPrimaryColor = Color(0xFF1E2B00),
        textColor = Color(0xFFF4FFE0),
        textSecondaryColor = Color(0xFFA1B381),
        meterPeakColor = Color(0xFFCCFF00)
    ),
    ICE_CYAN(
        id = "ice_cyan",
        displayName = "Alpine Arctic Cyan",
        subtitle = "Estilo Alpine F#1 Status & Focal",
        primaryColor = Color(0xFF00E5FF),
        accentColor = Color(0xFF80F3FF),
        backgroundColor = Color(0xFF040F12),
        surfaceColor = Color(0xFF091D24),
        cardColor = Color(0xFF0F2E38),
        onPrimaryColor = Color(0xFF002A30),
        textColor = Color(0xFFE0FCFF),
        textSecondaryColor = Color(0xFF7AAEB5),
        meterPeakColor = Color(0xFF18FFFF)
    ),
    VAPOR_PINK(
        id = "vapor_pink",
        displayName = "Vaporwave Neon Pink",
        subtitle = "Estilo Car Show Night Glow",
        primaryColor = Color(0xFFFF2A85),
        accentColor = Color(0xFFFF70A6),
        backgroundColor = Color(0xFF12050E),
        surfaceColor = Color(0xFF210A1A),
        cardColor = Color(0xFF331028),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFFFEBF4),
        textSecondaryColor = Color(0xFFB5809D),
        meterPeakColor = Color(0xFFFF1493)
    ),
    TITANIUM_SQL(
        id = "titanium_sql",
        displayName = "Titanium SQL Studio",
        subtitle = "Estilo Monoblock Aluminio & Calidad",
        primaryColor = Color(0xFFD1D5DB),
        accentColor = Color(0xFF9CA3AF),
        backgroundColor = Color(0xFF0F1115),
        surfaceColor = Color(0xFF181B20),
        cardColor = Color(0xFF232730),
        onPrimaryColor = Color(0xFF111827),
        textColor = Color(0xFFF9FAFB),
        textSecondaryColor = Color(0xFF9CA3AF),
        meterPeakColor = Color(0xFFE5E7EB)
    ),
    TOXIC_YELLOW(
        id = "toxic_yellow",
        displayName = "Optima Danger Yellow",
        subtitle = "Estilo Optima Yellow Top & 16V SPL",
        primaryColor = Color(0xFFFFEA00),
        accentColor = Color(0xFFFFF176),
        backgroundColor = Color(0xFF121203),
        surfaceColor = Color(0xFF212108),
        cardColor = Color(0xFF33330C),
        onPrimaryColor = Color(0xFF262300),
        textColor = Color(0xFFFFFFE0),
        textSecondaryColor = Color(0xFFB5B37D),
        meterPeakColor = Color(0xFFFFD600)
    ),
    MAGMA_BURST(
        id = "magma_burst",
        displayName = "Magma Overload",
        subtitle = "Estilo Bobina Hirviendo & 5000W RMS",
        primaryColor = Color(0xFFFF3D00),
        accentColor = Color(0xFFFF8A65),
        backgroundColor = Color(0xFF140704),
        surfaceColor = Color(0xFF240D07),
        cardColor = Color(0xFF38150B),
        onPrimaryColor = Color(0xFFFFFFFF),
        textColor = Color(0xFFFFEBE5),
        textSecondaryColor = Color(0xFFB8857B),
        meterPeakColor = Color(0xFFDD2C00)
    )
}
